apiVersion: apps/v1
kind: Deployment
metadata:
	name: webapp
spec:
	replicas: 2
	template:
		metadata:
			labels:
				app: webapp
		spec:
			containers:
			- name: webapp
				image: webapp:latest
				ports:
				- containerPort: 8080
	selector:
		matchLabels:
			app: webapp