apiVersion: v1
kind: Pod
metadata:
    name: webapp
    labels:
        name: webapp
spec:
    containers:
        - name: simple-webapp
          image: webapp
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config-map