apiVersion: v1
kind: Pod
metadata:
		name: webapp
		labels:
				name: webapp
spec:
		serviceAccountName: web-sa
		containers:
			- name: simple-webapp
				image: webapp
				ports:
					- containerPort: 8080
				envFrom:
					- configMapRef:
							name: config-map
				#Alternative
				- env: 
					- name: APP_COLOR
						valueFrom:
							configMapKeyRef:
								name: webapp-config-map
								key: APP_COLOR
		securityContent:
			runAsUser: 1010
			capabilities:
				add: ["SYS_TIME"]
		resources:
			requests:
				cpu: "1"
			limits:
				cpu: "2"
		nodeSelector:
			size: Large
		affinity:
			nodeAffinity:
				requiredDuringSchedulingIgnoredDuringExecution:
					nodeSelectorTerms:
						- matchExpressions:
						  	- key: node-role.kubernetes.io/control-plane
								  operator: Exists
			
					
					
					