apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - targetPort: 80 # port on the pod
      port: 80  # service port
      nodePort: 30008 #port on the node
  selector:
    app: myapp

#cluster ip

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80  
  selector:
    app: myapp
    type: backend